apiVersion: apps/v1
kind: Deployment
metadata:
  name: ide-operator
  namespace: part-rde
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ide-operator
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 90d7fb9657ecd3bf9396eb209a76882c
      labels:
        app: ide-operator
    spec:
      serviceAccountName: cluster-admin-sa
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: ide-operator
        image: amdp-registry.skamdp.org/mydev-ywyi/ide-operator:2.0.0
        imagePullPolicy: Always
        securityContext:
            runAsUser: 0
            privileged: true
        env:
        - name: LOGGING_LEVEL
          value: INFO
        - name: COMDEV_PVC_NAME
          value: "com-dev-pvc"
        - name: USER_STORAGE_CLASS_NAME
          value: "gp2"
        - name: VSCODE_IMAGE_PATH
          value: "amdp-registry.skamdp.org/mydev-ywyi/devplace-vscode-server:2.4220"
        - name: SSHSERVER_IMAGE_PATH
          value: "amdp-registry.skamdp.org/mydev-ywyi/ssh-with-k9s-extend:1.0.1"
        - name: WETTY_IMAGE_PATH
          value: "amdp-registry.skamdp.org/mydev-ywyi/wetty-with-k9s:1.1"
        - name: NOTEBOOK_IMAGE_PATH
          value: "amdp-registry.skamdp.org/mydev-ywyi/devplace-notebook:1.0.10"
