apiVersion: v1
kind: Service
metadata:
  name: ide-operator-service
  labels:
    app: ide-operator
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080  
  selector:
    app: ide-operator


