apiVersion: v1
kind: Service
metadata:
  name: ide-operator-service
spec:
  selector:
    app: ide-operator
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


