apiVersion: v1
kind: Service
metadata:
  name: ideconfig-operator-service
  namespace: part-rde
spec:
  selector:
    app: ideconfig-operator
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


