apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sk000-my-app-kustomize
  namespace: skala-argocd
spec:
  destination:
    namespace: skala-practice
    server: https://96BD83E8CE5CE0396D006BC5CEB350B0.gr7.ap-northeast-2.eks.amazonaws.com
  project: skala
  source:
    path: kustomize/overlays/dev
    repoURL: https://github.com/rde-devplace/devops-source.git
    targetRevision: HEAD
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=background

    
