server:
  port: 9090
logging:
  level:
    ROOT: INFO

spring:
  profiles:
    active: local
  application:
    name: ide-operator

springdoc:
  api-docs:
    path: /api/ide-configs/api-docs
    title: Devplace manager API
    description: This Application create and manage ide config.
  swagger-ui:
    path: /api/ide-configs/swagger-ui.html
---
spring:
  config:
    activate:
      on-profile: local
ide:
  ide-proxy-domain: "kube-proxy.amdp-dev.skamdp.org"
  comdev:
    pvcName: com-dev-pvc
  user:
    storageClassName: gp2
  vscode:
    image: "amdp-registry.skamdp.org/mydev-ywyi/devplace-vscode-server:2.4220"
  sshserver:
    image: "amdp-registry.skamdp.org/mydev-ywyi/ssh-with-k9s-extend:1.0.1"
  wetty:
    image: "amdp-registry.skamdp.org/mydev-ywyi/wetty-with-k9s:1.1"
  notebook:
    image: "amdp-registry.skamdp.org/mydev-ywyi/devplace-notebook:1.0.10"

---
logging:
  level:
    ROOT: ${LOGGING_LEVEL}
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080
ide:
  ide-proxy-domain: ${IDE_PROXY_DOMAIN}
  comdev:
    pvcName: ${COMDEV_PVC_NAME}
  user:
    storageClassName: ${USER_STORAGE_CLASS_NAME}
  vscode:
    image: ${VSCODE_IMAGE_PATH}
  sshserver:
    image: ${SSHSERVER_IMAGE_PATH}
  wetty:
    image: ${WETTY_IMAGE_PATH}
  notebook:
    image: ${NOTEBOOK_IMAGE_PATH}

