server:
  port: 9090
logging:
  level:
    ROOT: INFO

spring:
  profiles:
    active: local
  application:
    name: ide-operator

springdoc:
  api-docs:
    path: /api-docs
    title: Devplace manager API
    description: This Application create and manage ide config.
  swagger-ui:
    path: /swagger-ui.html
---
spring:
  config:
    activate:
      on-profile: local
ide:
  comdev:
    pvcName: com-dev-pvc
  user:
    storageClassName: gp2
  vscode:
    image: "amdp-registry.skamdp.org/mydev-ywyi/amdp-vscode-server:2.1"
  sshserver:
    image: "amdp-registry.skamdp.org/mydev-ywyi/ssh-with-k9s-extend:1.0"
  wetty:
    image: "amdp-registry.skamdp.org/mydev-ywyi/wetty-with-k9s:1.1"

---
logging:
  level:
    ROOT: ${LOGGING_LEVEL}
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080
ide:
  comdev:
    pvcName: ${COMDEV_PVC_NAME}
  user:
    storageClassName: ${USER_STORAGE_CLASS_NAME}
  vscode:
    image: ${VSCODE_IMAGE_PATH}
  sshserver:
    image: ${SSHSERVER_IMAGE_PATH}
  wetty:
    image: ${WETTY_IMAGE_PATH}


